/* Auto-generated by scripts/scaffold-app-routes.mjs — do not edit */
export { default } from "@/app/admin/student-resources/key-dates/page";
export * from "@/app/admin/student-resources/key-dates/page";
