/* Auto-generated by scripts/scaffold-app-routes.mjs — do not edit */
export { default } from "@/app/admin/student-resources/study-abroad-facts/page";
export * from "@/app/admin/student-resources/study-abroad-facts/page";
