/* Auto-generated by scripts/scaffold-app-routes.mjs — do not edit */
export { default } from "@/app/(public)/purpleevents/session/[id]/page";
export * from "@/app/(public)/purpleevents/session/[id]/page";
