/* Auto-generated by scripts/scaffold-app-routes.mjs — do not edit */
export { default } from "@/app/(public)/programsfull/program/[id]/page";
export * from "@/app/(public)/programsfull/program/[id]/page";
